# Generated by Django 6.0 on 2026-01-05 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setups.genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='setups.band')),
            ],
            options={
                'ordering': ['band__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setups.band')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setups.genre')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_setups', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setups.song')),
            ],
            options={
                'ordering': ['-is_favorite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalChainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, help_text='Notes about this gear in this setup')),
                ('owned_gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.ownedgear')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_chain', to='setups.setup')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('setup', 'owned_gear')},
            },
        ),
    ]
