# Generated by Django 6.0 on 2026-01-05 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_unknown', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Amplifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amp_type', models.CharField(choices=[('TUBE', 'Tube'), ('SOLID_STATE', 'Solid State'), ('MODELING', 'Modeling'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('wattage', models.IntegerField(help_text='Power in watts')),
                ('has_effects_loop', models.BooleanField(default=False)),
                ('available_controls', models.JSONField(blank=True, default=list)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='equipment.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guitar_type', models.CharField(choices=[('STRAT', 'Stratocaster'), ('TELE', 'Telecaster'), ('LES_PAUL', 'Les Paul'), ('SG', 'SG'), ('OTHER', 'Other')], max_length=20)),
                ('num_strings', models.IntegerField(default=6)),
                ('pickup_config', models.CharField(blank=True, max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='equipment.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedal_type', models.CharField(choices=[('DISTORTION', 'Distortion'), ('OVERDRIVE', 'Overdrive'), ('FUZZ', 'Fuzz'), ('DELAY', 'Delay'), ('REVERB', 'Reverb'), ('CHORUS', 'Chorus'), ('OTHER', 'Other')], max_length=20)),
                ('available_controls', models.JSONField(blank=True, default=list)),
                ('default_settings', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='equipment.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OwnedGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('is_favorite', models.BooleanField(default=False)),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amplifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.amplifier')),
                ('guitar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.guitar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gear', to=settings.AUTH_USER_MODEL)),
                ('pedal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.pedal')),
            ],
            options={
                'ordering': ['-is_favorite', '-created_at'],
            },
        ),
    ]
